// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: kogo.proto

package kogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowOnlyRead bool `protobuf:"varint,1,opt,name=showOnlyRead,proto3" json:"showOnlyRead,omitempty"`
}

func (x *BooksRequest) Reset() {
	*x = BooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksRequest) ProtoMessage() {}

func (x *BooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksRequest.ProtoReflect.Descriptor instead.
func (*BooksRequest) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{0}
}

func (x *BooksRequest) GetShowOnlyRead() bool {
	if x != nil {
		return x.ShowOnlyRead
	}
	return false
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string  `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Author    string  `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	HoursRead float32 `protobuf:"fixed32,3,opt,name=HoursRead,proto3" json:"HoursRead,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetHoursRead() float32 {
	if x != nil {
		return x.HoursRead
	}
	return 0
}

var File_kogo_proto protoreflect.FileDescriptor

var file_kogo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x6f,
	0x67, 0x6f, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x4f, 0x6e,
	0x6c, 0x79, 0x52, 0x65, 0x61, 0x64, 0x22, 0x52, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x61, 0x64, 0x32, 0x3a, 0x0a, 0x08, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x12, 0x12, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kogo_proto_rawDescOnce sync.Once
	file_kogo_proto_rawDescData = file_kogo_proto_rawDesc
)

func file_kogo_proto_rawDescGZIP() []byte {
	file_kogo_proto_rawDescOnce.Do(func() {
		file_kogo_proto_rawDescData = protoimpl.X.CompressGZIP(file_kogo_proto_rawDescData)
	})
	return file_kogo_proto_rawDescData
}

var file_kogo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kogo_proto_goTypes = []interface{}{
	(*BooksRequest)(nil), // 0: kogo.BooksRequest
	(*Book)(nil),         // 1: kogo.Book
}
var file_kogo_proto_depIdxs = []int32{
	0, // 0: kogo.Activity.GetBooks:input_type -> kogo.BooksRequest
	1, // 1: kogo.Activity.GetBooks:output_type -> kogo.Book
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kogo_proto_init() }
func file_kogo_proto_init() {
	if File_kogo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kogo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kogo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kogo_proto_goTypes,
		DependencyIndexes: file_kogo_proto_depIdxs,
		MessageInfos:      file_kogo_proto_msgTypes,
	}.Build()
	File_kogo_proto = out.File
	file_kogo_proto_rawDesc = nil
	file_kogo_proto_goTypes = nil
	file_kogo_proto_depIdxs = nil
}
