// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: kogo.proto

package kogo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BooksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowOnlyRead bool `protobuf:"varint,1,opt,name=showOnlyRead,proto3" json:"showOnlyRead,omitempty"`
}

func (x *BooksRequest) Reset() {
	*x = BooksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksRequest) ProtoMessage() {}

func (x *BooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksRequest.ProtoReflect.Descriptor instead.
func (*BooksRequest) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{0}
}

func (x *BooksRequest) GetShowOnlyRead() bool {
	if x != nil {
		return x.ShowOnlyRead
	}
	return false
}

type BookCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BookCountRequest) Reset() {
	*x = BookCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCountRequest) ProtoMessage() {}

func (x *BookCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCountRequest.ProtoReflect.Descriptor instead.
func (*BookCountRequest) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{1}
}

type BookCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BookCountResponse) Reset() {
	*x = BookCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCountResponse) ProtoMessage() {}

func (x *BookCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCountResponse.ProtoReflect.Descriptor instead.
func (*BookCountResponse) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{2}
}

func (x *BookCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BackupDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *BackupDatabaseRequest) Reset() {
	*x = BackupDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseRequest) ProtoMessage() {}

func (x *BackupDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseRequest.ProtoReflect.Descriptor instead.
func (*BackupDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{3}
}

func (x *BackupDatabaseRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BackupDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BackupDatabaseResponse) Reset() {
	*x = BackupDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseResponse) ProtoMessage() {}

func (x *BackupDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseResponse.ProtoReflect.Descriptor instead.
func (*BackupDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{4}
}

func (x *BackupDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OfflineSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverwriteExistingUser bool `protobuf:"varint,1,opt,name=overwriteExistingUser,proto3" json:"overwriteExistingUser,omitempty"`
}

func (x *OfflineSetupRequest) Reset() {
	*x = OfflineSetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineSetupRequest) ProtoMessage() {}

func (x *OfflineSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineSetupRequest.ProtoReflect.Descriptor instead.
func (*OfflineSetupRequest) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{5}
}

func (x *OfflineSetupRequest) GetOverwriteExistingUser() bool {
	if x != nil {
		return x.OverwriteExistingUser
	}
	return false
}

type OfflineSetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success             bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExistingUserPresent bool `protobuf:"varint,2,opt,name=existingUserPresent,proto3" json:"existingUserPresent,omitempty"`
}

func (x *OfflineSetupResponse) Reset() {
	*x = OfflineSetupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineSetupResponse) ProtoMessage() {}

func (x *OfflineSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineSetupResponse.ProtoReflect.Descriptor instead.
func (*OfflineSetupResponse) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{6}
}

func (x *OfflineSetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OfflineSetupResponse) GetExistingUserPresent() bool {
	if x != nil {
		return x.ExistingUserPresent
	}
	return false
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string  `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Author      string  `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	HoursRead   float32 `protobuf:"fixed32,3,opt,name=HoursRead,proto3" json:"HoursRead,omitempty"`
	PercentRead int32   `protobuf:"varint,4,opt,name=PercentRead,proto3" json:"PercentRead,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kogo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_kogo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_kogo_proto_rawDescGZIP(), []int{7}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetHoursRead() float32 {
	if x != nil {
		return x.HoursRead
	}
	return 0
}

func (x *Book) GetPercentRead() int32 {
	if x != nil {
		return x.PercentRead
	}
	return 0
}

var File_kogo_proto protoreflect.FileDescriptor

var file_kogo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x6f,
	0x67, 0x6f, 0x22, 0x32, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x4f, 0x6e,
	0x6c, 0x79, 0x52, 0x65, 0x61, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x11, 0x42, 0x6f,
	0x6f, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a, 0x15, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x32, 0x0a, 0x16, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a,
	0x15, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x6f, 0x76,
	0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x14, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x13, 0x65, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x64, 0x32, 0x95, 0x02,
	0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x12, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x6b, 0x6f, 0x67,
	0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x6b, 0x6f, 0x67,
	0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a,
	0x0e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x1b, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b,
	0x6f, 0x67, 0x6f, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x19, 0x2e, 0x6b,
	0x6f, 0x67, 0x6f, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x6f, 0x67, 0x6f, 0x2e, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kogo_proto_rawDescOnce sync.Once
	file_kogo_proto_rawDescData = file_kogo_proto_rawDesc
)

func file_kogo_proto_rawDescGZIP() []byte {
	file_kogo_proto_rawDescOnce.Do(func() {
		file_kogo_proto_rawDescData = protoimpl.X.CompressGZIP(file_kogo_proto_rawDescData)
	})
	return file_kogo_proto_rawDescData
}

var file_kogo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kogo_proto_goTypes = []interface{}{
	(*BooksRequest)(nil),           // 0: kogo.BooksRequest
	(*BookCountRequest)(nil),       // 1: kogo.BookCountRequest
	(*BookCountResponse)(nil),      // 2: kogo.BookCountResponse
	(*BackupDatabaseRequest)(nil),  // 3: kogo.BackupDatabaseRequest
	(*BackupDatabaseResponse)(nil), // 4: kogo.BackupDatabaseResponse
	(*OfflineSetupRequest)(nil),    // 5: kogo.OfflineSetupRequest
	(*OfflineSetupResponse)(nil),   // 6: kogo.OfflineSetupResponse
	(*Book)(nil),                   // 7: kogo.Book
}
var file_kogo_proto_depIdxs = []int32{
	0, // 0: kogo.Activity.GetBooks:input_type -> kogo.BooksRequest
	1, // 1: kogo.Activity.GetBookCount:input_type -> kogo.BookCountRequest
	3, // 2: kogo.Activity.BackupDatabase:input_type -> kogo.BackupDatabaseRequest
	5, // 3: kogo.Activity.OfflineSetup:input_type -> kogo.OfflineSetupRequest
	7, // 4: kogo.Activity.GetBooks:output_type -> kogo.Book
	2, // 5: kogo.Activity.GetBookCount:output_type -> kogo.BookCountResponse
	4, // 6: kogo.Activity.BackupDatabase:output_type -> kogo.BackupDatabaseResponse
	6, // 7: kogo.Activity.OfflineSetup:output_type -> kogo.OfflineSetupResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kogo_proto_init() }
func file_kogo_proto_init() {
	if File_kogo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kogo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineSetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineSetupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kogo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kogo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kogo_proto_goTypes,
		DependencyIndexes: file_kogo_proto_depIdxs,
		MessageInfos:      file_kogo_proto_msgTypes,
	}.Build()
	File_kogo_proto = out.File
	file_kogo_proto_rawDesc = nil
	file_kogo_proto_goTypes = nil
	file_kogo_proto_depIdxs = nil
}
